<a href="https://colab.research.google.com/github/Abhinav1507/Abhinav/blob/master/ML1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


In [3]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
import numpy as np
np_array=np.array(data)
print('np',np_array)
x_np=torch.from_numpy(np_array)
print('x_np',x_np)

np [[1 2]
 [3 4]]
x_np tensor([[1, 2],
        [3, 4]])


In [3]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
print(rand_tensor,rand_tensor[1][0])
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.0401, 0.1564, 0.9056],
        [0.0829, 0.9709, 0.9833]]) tensor(0.0829)
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [4]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [7]:
tensor = torch.ones(4, 4)
tensor[:,2] = 0
print(tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


In [2]:
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 92.0MB/s]


In [3]:
prediction = model(data) # forward pass
loss = (prediction - labels).sum()
loss.backward() # backward pass

In [4]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)
optim.step() #gradient descent

In [5]:

a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
print(a.dim())
print(b)
print(Q)

1
tensor([6., 4.], requires_grad=True)
tensor([-12.,  65.], grad_fn=<SubBackward0>)


In [6]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)
# check if collected gradients are correct
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])


In [7]:

model = resnet18(weights=ResNet18_Weights.DEFAULT)

# Freeze all the parameters in the network
for param in model.parameters():
    param.requires_grad = False

In [8]:
model.fc = torch.nn.Linear(512, 10)
# Optimize only the classifier
optimizer = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

In [2]:
import torch.nn.functional as F
import torch.nn as nn


In [3]:
class model(nn.Module):
  def __init__(self):
     super(model,self).__init__()
     self.con1=nn.Conv2d(1,6,5)
     self.con2=nn.Conv2d(6,16,5)
     self.fc1=nn.Linear(16*5*5,120)
     self.fc2=nn.Linear(120,84)
     self.fc3=nn.Linear(84,10)
  def forward(self,x):
    x=F.max_pool2d(F.relu(self.con1(x)),(2,2))
    x=F.max_pool2d(F.relu(self.con2(x)),2)
    x=torch.flatten(x,1)
    x=F.relu(self.fc1(x))
    x=F.relu(self.fc2(x))
    x=self.fc3(x)
    return x
Model=model()
print(Model)

model(
  (con1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (con2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [4]:
params=list(Model.parameters())
print(len(params))
print(params[0].size())
print(params[1].size())
print(params[2].size())
print(params[3].size())
print(params[4].size())

10
torch.Size([6, 1, 5, 5])
torch.Size([6])
torch.Size([16, 6, 5, 5])
torch.Size([16])
torch.Size([120, 400])


In [6]:
input = torch.randn(1, 1, 32, 32)
out = Model(input)
print(out)

tensor([[ 0.0827,  0.0665, -0.0589,  0.1213, -0.0730,  0.0393, -0.0566, -0.0944,
         -0.1930, -0.0641]], grad_fn=<AddmmBackward0>)


In [8]:
Model.zero_grad()
out.backward(torch.randn(1, 10))

In [11]:
Output=Model(input)
print(input)
print(Output)
target=torch.randn(10)
print(target)
target=target.view(1,-1)
print(target)

tensor([[[[-0.1603,  0.9701, -2.2615,  ..., -0.7057, -2.4273,  0.5723],
          [-0.4084, -1.0999, -1.2365,  ...,  1.1190, -0.2367, -0.4893],
          [-0.2592, -1.2274, -0.0718,  ...,  1.7171,  1.5632, -0.6980],
          ...,
          [-0.3272, -0.2910,  0.9936,  ..., -0.5467,  1.4468, -0.8760],
          [-0.2905, -0.0468, -1.3266,  ...,  1.6294,  1.2492,  1.0890],
          [ 1.0374,  0.1132, -0.5495,  ...,  1.1500, -0.6615, -0.1864]]]])
tensor([[ 0.0827,  0.0665, -0.0589,  0.1213, -0.0730,  0.0393, -0.0566, -0.0944,
         -0.1930, -0.0641]], grad_fn=<AddmmBackward0>)
tensor([ 0.4331,  1.0656,  1.1408, -0.3329,  1.4527,  0.5441,  0.3320,  0.6784,
        -1.6454,  0.6372])
tensor([[ 0.4331,  1.0656,  1.1408, -0.3329,  1.4527,  0.5441,  0.3320,  0.6784,
         -1.6454,  0.6372]])


In [12]:
loss_f=nn.MSELoss()
loss=loss_f(Output,target)
print(loss)

tensor(0.8699, grad_fn=<MseLossBackward0>)


In [13]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [16]:
Model.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(Model.con1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(Model.con1.bias.grad)
print(Model.con1.weight.grad)

conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor([ 0.0048, -0.0096,  0.0026,  0.0022,  0.0037, -0.0012])
tensor([[[[ 9.2842e-03,  1.8399e-02, -8.6782e-03,  1.7937e-03,  4.8161e-03],
          [ 8.6810e-03,  1.4714e-02,  8.8585e-03,  8.4169e-03,  1.6128e-03],
          [-1.6689e-02,  3.1001e-03, -1.0274e-02,  6.0423e-03,  4.6536e-03],
          [-2.2217e-04, -1.0975e-02, -2.6087e-02, -1.0829e-02, -2.5327e-02],
          [ 2.4864e-03,  9.6773e-03,  5.4787e-03, -4.6205e-03, -3.0900e-02]]],


        [[[ 5.3214e-03,  1.6349e-02, -2.3134e-03,  1.6643e-02,  2.1718e-02],
          [-8.6338e-04, -7.2503e-03, -1.0554e-02, -3.7049e-03, -5.0813e-03],
          [ 1.7225e-02,  1.0872e-04, -8.7709e-03,  1.9788e-02,  1.9220e-02],
          [ 4.4933e-03,  1.7511e-02, -5.4992e-03,  1.3923e-02, -3.0992e-02],
          [ 2.4515e-02, -1.8275e-02,  9.8577e-03,  1.4895e-02,  1.0844e-02]]],


        [[[-2.8309e-03,  1.3662e-02, -9.1567e-03, -3.0983e-05,  1.7765e-03],
          [-4.

In [18]:
learning_rate = 0.01
for f in Model.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [19]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(Model.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = Model(input)
loss = loss_f(output, target)
loss.backward()
optimizer.step()    # Does the update